In [ ]:
import torch
a = torch.tensor(
    [[1.0, 2.0, 3.0],
     [4.0, 5.0, 6.0]])

print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)

torch.eye(3)

In [ ]:
import numpy as np
x = torch.from_numpy(np.array([1.0, 2.0]))

print(x.dtype)
print(x.float().dtype)

In [ ]:
x = torch.arange(12)
x.reshape(2,2,3)

In [44]:
a = torch.tensor([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]])
b = torch.tensor([[2.0, 6.0],
                  [3.0, 3.0],
                  [2.0, 1.0]])

a @ b


m = torch.zeros(3,1)
print(m)

tensor([[0.],
        [0.],
        [0.]])


In [45]:
b = torch.randn(1, 3)
print(b.squeeze().shape)      # (3,)

c = torch.randn(3, 1)
print(c.squeeze().shape)      # (3,)

d = torch.randn(1, 3, 1)
print(d.squeeze().shape)      # (3,) — прибрав обидві
print(d.squeeze(0).shape)     # (3, 1) — прибрав тільки нульовий
print(d.squeeze(-1).shape)    # (1, 3) — тільки останній

torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3, 1])
torch.Size([1, 3])


In [47]:
import torch.nn as nn

pred = torch.randn(10, 1)
print(pred)
true = torch.randn(10)
print(true)
print("pred:", pred.shape)          # (10, 1)
print("true:", true.shape)          # (10,)

print("різниця:", (pred - true).shape)

tensor([[ 0.8315],
        [-1.0388],
        [-0.4126],
        [-1.3042],
        [ 0.6919],
        [ 0.7464],
        [ 0.1639],
        [ 0.8345],
        [ 0.1675],
        [-0.5976]])
tensor([-0.6895,  0.0357,  1.5960, -1.6437,  2.2203, -0.0359, -0.6456, -0.8626,
         0.3838,  0.0767])
pred: torch.Size([10, 1])
true: torch.Size([10])
різниця: torch.Size([10, 10])


In [37]:
x = torch.tensor(3.0, requires_grad = True)
y = x ** 2
y.backward()
print(x.grad)

tensor(6.)


In [ ]:
x = torch.tensor(3.0, requires_grad = True)
y = 3 * x ** 2 + 2 * x
y.backward()
print(x.grad)

In [36]:
x = torch.tensor(0.0, requires_grad=True)
lr = 0.01

for step in range(100):
    loss = (x - 5)**2

    loss.backward()

    with torch.no_grad():
        x -= lr * x.grad
    x.grad.zero_()
    if step % 10 == 0:
        print(f"step : {step}, loss : {loss.item():.4f}, x = {x.item():.4f}")

step : 0, loss : 25.0000, x = 0.1000
step : 10, loss : 0.1795, x = 5.2851
step : 20, loss : 23.7056, x = 9.9883
step : 30, loss : 3.7283, x = 6.2590
step : 40, loss : 18.2425, x = 0.4015
step : 50, loss : 10.5822, x = 2.3175
step : 60, loss : 10.6546, x = 8.7681
step : 70, loss : 18.1770, x = 8.8490
step : 80, loss : 3.7806, x = 2.4233
step : 90, loss : 23.6715, x = 0.3534
